language: node_js
node_js:
- '0.10'
services: 
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: QVqbzrzSsKYvsc1nl4DrgCHEsiDFJbFWsSc1KPCSyl0+QpcReXj0TKoJLZSjqkX0PPtDJvcqRDDbaVE1QS2mgRdOPYTA7XeJtU3gmHrj0aNb1Q62a3/iCH+fIxnKguFj3G4hEHuNrYQv8/GhDd30f1XAD1hu/Op3TF/2WFN+LwA=
  app: pathlete
  on: master
